### ISSUE TITLE
更底层的热更新实现

### ISSUE THREAD

**Issue by wjy000** [githubwing/HotXposed#2]
哥们,你将 XposedHelpers.findAndHookMethod hook代码写在主程序中,普通的代码使用dex加载这个没问题,
但是如果需要修改hook的类或者方法,仍然需要重启

所以我想将所有的hook 方法都写到dex中,主程序只实现handleLoadPackage这一个方法,其他的都交给dex去动态加载,但是我这样做了会报错,不知道这样做,原理是能不能通过?

**Comment by githubwing** [comment]
你把classloader传到DexFile里面试一下

**Comment by githubwing** [comment]
已更新~
